### ISSUE TITLE
@todo

### ISSUE THREAD

**Issue by thefarang** [thefarang/concha_twitter#10]
- [ ] Use NODE_DIR to cleanup the pathname lookups
- [ ] Remove dependency on the Twitter schema outside of twitter API
- [ ] Modify test code to use the services/ folder. The support/ folder should only contain stubs
